# Generated by Django 2.0.3 on 2019-01-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1)),
                ('mobile_1', models.CharField(max_length=15)),
                ('mobile_2', models.CharField(max_length=15)),
                ('mobile_3', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('location', models.TextField()),
            ],
        ),
    ]
